#!/bin/sh

useradd -m -s /bin/bash user

usergroups="audio video sudo"
for grp in $usergroups; do
	gpasswd -a user $grp
done

chown -R user:users /home/user

rm -f /usr/share/themes/default
ln -s /usr/share/themes/alpha/ /usr/share/themes/default

mkdir -p /var/lib/dsme
echo "USER" > /var/lib/dsme/saved_state

mkdir -p /etc/sudoers.d
echo "user    ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/maemo
