#!/bin/sh
USER=user
GROUPS="audio video sudo"

if ! id -u $USER 2>/dev/null ; then
  echo "Adding user '$USER'"
  useradd -m -s /bin/bash $USER

  for group in $GROUPS; do
          gpasswd -a $USER $group
  done
fi

ln -svnf alpha /usr/share/themes/default

install -d /var/lib/dsme
[ ! -f /var/lib/dsme/saved_state ] && echo "USER" > /var/lib/dsme/saved_state

if [ ! -f /etc/sudoers.d/maemo ]; then
  echo "Adding maemo sudoers file"
  install -d /etc/sudoers.d
  echo "$USER    ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/maemo
  chmod 0440 /etc/sudoers.d/maemo
fi
